In [8]:
import numpy as np
import pandas as pd


What is numpy?
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

Numpy Arrays Vs Python Sequences
NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

## creating numpy array

In [9]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [10]:
type(arr)

numpy.ndarray

In [15]:
#2d array
arr2d = np.array([[1,2,3],[11,22,33]])
arr2d

array([[ 1,  2,  3],
       [11, 22, 33]])

In [16]:
type(arr2d)

numpy.ndarray

In [21]:
#3d array
arr3d = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[100,101,102,103,104],[105,106,107,108,109]]])
arr3d

array([[[  1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10]],

       [[100, 101, 102, 103, 104],
        [105, 106, 107, 108, 109]]])

In [25]:
np.array([1,2,3,4,9.99]).dtype
np.array([1,2,3,4,5],dtype='float').dtype

dtype('float64')

In [31]:
#np.arange
#reshape

np.arange(1,100,9.9)
np.arange(0,16).reshape(4,4).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [37]:
# np.ones
# np.zero
# np.random
# np.linespace  return array element with proper space
# np.identity  return the identity array 

np.ones((2,3))
np.zeros((4,4,4))
np.random.random((3,4))

array([[0.6963633 , 0.87862417, 0.33010532, 0.2301981 ],
       [0.47279318, 0.38167086, 0.20253722, 0.13510485],
       [0.84905454, 0.01170273, 0.75254786, 0.8089514 ]])

In [42]:
np.linspace(1,10,5,dtype='int')

array([ 1,  3,  5,  7, 10])

In [43]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Array Attribute